name: Digital Nomad
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38264
title: Digital Nomad
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070604'
    - '#bcc2b8'
    - '#ffffec'
    - '#8c918d'
    - '#4a4c41'
  brandStrength: 0.6875
  lightness: 0.5895288
  saturation: 0.8125
  rhythmicContrast: 0.512511
purpose: []
